### PR TITLE
Avoid unnecessary loop

### LINKED ISSUE #121: Extension slows down firefox quantum
I'm using Ubuntu 18.04 and Firefox quantum 60.0.1  

When I'm researching PRs page a message popup appears at the top of the viewport  

image  

And it really makes it very slow. When disabling the extension this page is loading faster

### LINKED ISSUE #131: Conflict with the userscript 'GitHub Search Autocomplete' - the browser becomes very sluggish when typing anything in searchboxes
I have noticed in both Firefox 67/Chrome 74 (win 10) that with the extension enabled, 
trying to type anything in a searchbox, makes the browser become very sluggish.

STR (occurs consistently)
- in a fresh Firefox/Chrome profile with only GitHub Hovercard 1.8.0 + Tampermonkey 4.8.41 with the following userscript: [GitHub Search Autocomplete](https://greasyfork.org/en/scripts/28592-github-search-autocomplete)
- open e.g. https://github.com/Justineo/github-hovercard/issues
- click inside either the top 'Search or jump to' searchbox or the Issues searchbox 
and try to type anything: the characters are displayed very slowly.
- Also, try to select your typed word via doubleclick: the word will become selected after 5+ sec in my system!!
- Disabling GitHub Hovercard fixes the issue.

P.S. Also, kindly cc'ing @Mottie, author of the aforementioned userscript.
P.P.S. I've deleted my comment report in https://github.com/Justineo/github-hovercard/issues/121 as what I describe appears to be a conflict with a userscript, not an issue of the extension itself.

### LINKED ISSUE #133: [bug] cpu usage up to 100% when switch between some page
steps:

1. open https://github.com/MicrosoftDocs/Console-Docs/tree/master/docs
1. click file `TOC.md`

### LINKED ISSUE #140: Huge slowdown / page freeze when viewing large diffs in PR (Conflict w/ Refined GH ext)
Attempting to expand a diff with 830 changes appears to work fine until you attempt to scroll down- the page seems to truncate and end in whiteness and at that point scroll gets stuck and you cannot do anything on the page for 5-30s. Eventually the rest of the content loads up and behavior returns to normal.

Disabling hovercard extension and attempting to expand+view the diff again works as expected, perfectly acceptable performance on expand and scroll.

*edit*: Initially I had been blaming content.js before I realized it was never a dependency of this repo. The Refined Github extension uses it. Further testing on the 830 line diff reveals:
- Hovercard enabled alone causes **no noticeable performance hit**
- Refined Github enabled alone causes a **very slight performance hit**
- Both of them enabled together causes a **huge performance hit**. system CPU consumption jumps from 5% to 30-40% sustained, so likely 100% consumption of a single core.

So it's likely this is a conflict between the two extensions and how they listen for and process new content. I am really not sure if there is anything actionable here as neither extension's maintainers are responsible for the others, but Hovercard+Refined are two popular and no-brainer installs for anyone looking to augment the GH experience so I feel like this conflict may affect many whether they realize it or not. 

Chrome 79.0.3945.117 (current)

### LINKED ISSUE #141: Possible to disable plugin automatically when viewing code files?
Hey there,    
Love the plugin, I use it constantly and daily. I was wondering if it's possible to have the plugin automatically disable when viewing code files? More often than not, for some reason, on Firefox (not sure about Chrome) if I am in a repo and click on a code file, if the code file is any sort of moderate length, the plugin makes the browser hang and it comes up with the yellow bar at the top. Any time I hit disable, everything finishes loading just fine right away. Is it possible to just make the plugin not active in the first place on these types of pages?

Thanks,
-MH

### PR DESCRIPTION
**Pull request by fregante**
Fixes #121
Fixes #131 
Fixes #133 
Fixes #140
Fixes #141

(untested)

### CODE REVIEW

**Comment by aspiers** [comment]
Has anyone tested this yet?

**Comment by Justineo** [comment]
It turns out the piece of code here isn't the root cause the performance bottleneck. I've managed to refactored the code a little bit to using an async task queue while extracting metadata. Hopefully the new version will fix the current problem. Welcome to try it out and give some feedbacks!

**Comment by aspiers** [comment]
Thanks for the update. I've just upgraded to 1.9.0 and picked [a random source file](https://github.com/tstack/lnav/blob/master/m4/ax_with_curses.m4) to navigate to from Chrome on my low/medium-powered ChromeBook (Google Pixel Slate). With this script disabled it renders fine; however when I enable it, once I scroll beyond the first 100 lines or so of the file, the tab stops rendering and completely freezes, with Chrome's Task Manager showing that it is chewing up around 100% CPU. So I don't think it's fixed yet unfortunately.

**Comment by Justineo** [comment]
Oh, sorry to hear that. I don't have a low end device for test right now and I can't reproduce the hang up on the page you provided.

@fregante @darkred I saw your upvotes to @aspiers's comment. Do you share the same experience?

**Comment by aspiers** [comment]
@Justineo No low end device needed - I can reproduce on a 32GB machine with 8 Xeon 4GHz cores. However I think the key thing is to have [Refined GitHub](https://github.com/sindresorhus/refined-github) installed at the same time; if I disable that then the performance is OK so I think the problem is related to the combination of that with Hovercard.

**Comment by aspiers** [comment]
By the way I think the problem gets rapidly worse the longer the source file, so if you're having problems reproducing, maybe try a really long file.

**Comment by fregante** [comment]
I think the link with Refined GitHub is that this applies to changes to the DOM and possibly retriggers some heavy modifications by the Hovercard

**Comment by Justineo** [comment]
GitHub Hovercard is using `MutationObserver` to extract identifiable user/repo/issue/... contents. 

Because on GitHub there are so many possibilities where a mutation may happen (like loading async data or navigate to new pages with PJAX), I'm now observing `document.body` and try to extract information out of newly added elements. In observe options, I think it's necessary to observer with the option `subtree: true` otherwise we can only be notified when the direct children of `document.body` are added or removed, which would fail to find all newly added contents.

According to what I found, the current bottleneck for GitHub Hovercard to work with Refined GitHub is that on pages with very long source code, Refined GitHub may add many visible characters to visualize spaces, tabs, etc. This may cause us to receive huge amount of `MutationRecord`s and we are now trying to extract information out of every target node.

IMO there might be two possible solutions:

1. Exclude source code containers from extraction for GitHub Hovercard, apparently it won't work on contents like code comments anymore.
2. Figure out a way to identify such DOM modifications and skip extractions for them.

**Pull request closed without merging**
