### PR TITLE
1.9.3

### PR DESCRIPTION
**Pull request by TreyRuffy**
Two New Themes

I have added both a GitHub dark theme and One Dark theme

### CODE REVIEW

**Comment by Justineo** [comment]
Thank you! Can you remove the generated files and keep only the modified source files in this PR?

**Comment by TreyRuffy** [comment]
> 
> 
> Thank you! Can you remove the generated files and keep only the modified source files in this PR?

You got it

**Comment by TreyRuffy** [comment]
Is there anything else I need to change?

**Review by Justineo — APPROVED** [review]

**Comment by Justineo** [comment]
Thank you!

**Pull request merged**
